EXT2_FORMATTER :=
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S), Linux)
	EXT2_FORMATTER = mkfs
endif
ifeq ($(UNAME_S), Darwin)
	EXT2_FORMATTER = /usr/local/opt/e2fsprogs/sbin/mkfs.ext2
endif

AS=nasm
CPPC=i686-elf-g++
CC=i686-elf-gcc
AR=i686-elf-ar
ASFLAGS=-felf
QEMU=qemu-system-i386
QEMU_IMG=qemu-img
MOUNT_EXT2=fuse-ext2
MKDIR_P=mkdir -p

QEMUFLAGS=-vga std -serial mon:stdio -hda ${DISK}
LDFLAGS=-Wl,--gc-sections -ffreestanding -nostdlib -g
CFLAGS=-O3 -nostdlib -nostdinc -fno-builtin -fno-stack-protector -ffreestanding -m32 -Iinclude -fno-leading-underscore -Wno-write-strings
CPPFLAGS=-fno-use-cxa-atexit -fno-rtti -fno-exceptions

DISK=drive.img

ROOT_DIR=$(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))
KERNEL_SRC_DIR=$(ROOT_DIR)/kernel
USERSPACE_SRC_DIR=$(ROOT_DIR)/userspace
WISTERIALIB_SRC_DIR=$(ROOT_DIR)/Wisterialib

BUILD_DIR=$(ROOT_DIR)/build
KERNEL_BUILD_DIR=$(ROOT_DIR)/build/kernel
USERSPACE_BUILD_DIR=$(ROOT_DIR)/build/userspace
WISTERIALIB_BUILD_DIR=$(ROOT_DIR)/build/Wisterialib
LIBS_BUILD_DIR=$(USERSPACE_BUILD_DIR)/libs

TARGET_EXEC ?= WisteriaOS.bin
TARGET_EXEC_ISO ?= WisteriaOS.iso
TEST_EXEC ?= WisteriaOSTest.bin

WISTERIALIB=Wisterialib.a
